### ISSUE TITLE
A little bug in run_negDriver, forget to create the dictionary $OUTDIR

### ISSUE THREAD

**Issue by qingjian1991** [luisgls/SSB_selection#1]
Hi, Luis:

When running your code, you may miss to create the dictionary: *$OUTDIR*  in line 210 of **run_negDriver**.

```shell
##Add hugo name to file; line 210
if [ ! -d $OUTDIR ] 
then
	mkdir $OUTDIR
fi
```

You may just add a short code to create the dictionary *$OUTDIR*, like above.

Your Sincerely,

Qingjian

**Comment by luisgls** [comment]
Thanks Ill add it!
